### ISSUE TITLE
Add tests for skewness/kurtosis calculation

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1084]
New functionality which was contributed by @jlavileze in #1062 still needs to be properly tested.
In addition, we might want to move calculations of skewness/kurtosis out of the main stats loop given that it's not needed very often, and we don't want to hurt the performance of calculation of such crucial stats as `min`/`max`/`countna`.

**Comment by pradkrish** [comment]
How much of this is still left? Clearly, some tests need to be added. What about moving it out of the main stats loop thingy?

**Comment by oleksiyskononenko** [comment]
@pradkrish yes, these two functions are not exposed for some reason. It is nice that you got them both back on your PR.
As for the "moving it out of the main stats loop", I guess that was relevant to these changes https://github.com/h2oai/datatable/pull/1062/files Since that time the stats code was heavily refactored, I believe there is no more performance issue related to `.skew()`/`.kurt()`.
