### ISSUE TITLE
Error with groupby (referred to code in #1032 issue)

### ISSUE THREAD

**Issue by CarlosThinkBig** [h2oai/datatable#1091]
Hi,
I recently found your porting of `data.table` to Python. 
Thanks a lot for this!. I use it heavily in *R*.

I have just installed in an environment in my Mac machine to see its performance in Python (Python 3.6). And when I tried to reproduce your code you included in #1032  and I still get an error.

```Python
(ml_36) MESCO186015-203:~ co186015$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>> import datatable as dt
>>> from datatable import f, min, max
>>> f0 = dt.Frame({"color": ["red", "blue", "green", "red", "green"], "size": [5, 2, 7, 13, 0]})
>>> f0(select= [min(f.size), max(f.size)], groupby="color")
ValueError: Mismatched length in Column 1: found 1, expected 3
    File /anaconda3/envs/ml_36/lib/python3.6/site-packages/datatable/frame.py, line 497, in __call__()
         res = make_datatable(self, rows, select, groupby, sort, engine)
    File /anaconda3/envs/ml_36/lib/python3.6/site-packages/datatable/graph/__init__.py, line 97, in make_datatable()
         res_dt = ee.columns.to_datatable()
```

Thanks,
Carlos Ortega

**Comment by st-pasha** [comment]
Thanks, Carlos for your interest. As you have probably seen in #1032, that issue was closed only 5 days ago, whereas the latest stable release (0.5.0) was 11 days ago. So if you have installed `datatable` from pip, you probably don't have this fix yet.
You can check `dt.__git_revision__` variable to see the exact git commit from which your datatable was built.

If you do find that your `datatable` is 11 days old (commit `4e79667...`), then to get the latest version you'd need to install it from source. Alternatively, you can wait just a little bit, because we'll be releasing the next version today (if nothing goes wrong).

**Comment by CarlosThinkBig** [comment]
Thanks!
I will wait for the new version.
If I see the issue I will let you know.

Thanks again!
Carlos.

**Comment by CarlosThinkBig** [comment]
Hello,
I have just upgraded the module and everything works fine!.

```Python
>>> import datatable as dt
>>> from datatable import f, min, max
>>> f0 = dt.Frame({"color": ["red", "blue", "green", "red", "green"], "size": [5, 2, 7, 13, 0]})
>>> f0(select= [min(f.size), max(f.size)], groupby="color")
     color  min1(f2_size)  max1(f2_size)
---  -----  -------------  -------------
 0   blue               2              2
 1   green              0              7
 2   red                5             13

[3 rows x 3 columns]
```

Thanks!
Carlos.
