### ISSUE TITLE
Implement conversion of object columns into strings

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/datatable#1303]
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.astype.html

Example code this would replace:

```
    tr = dt.Frame(train_dt)
    to_delete = []
    for c in tr.names:
        if tr[c].ltypes[0] == dt.ltype.obj:
            try:
                tr = set_dt_col(tr, c, tr[c].topandas().astype('str', errors='raise'))
            except:
                loggerdata(logger, "Dropping object column from the training data: %s" % c)
                to_delete.append(c)
    if len(to_delete) > 0:
        del tr[:, to_delete]

    return tr
```

```
def set_dt_col(train_dt, name, value):
    if isinstance(name, int):
        name = train_dt.names[name]
    train_dt[name] = value
    return train_dt
```

**Comment by pseudotensor** [comment]
So, replace object columns as string if can (or in general, like pandas, replace with one type if can, and allow ignore of errors if can't, like pandas.)

**Comment by pseudotensor** [comment]
Key is to allow raise of error or ignore error.  In some places we need to raise, others ignore.

**Comment by st-pasha** [comment]
We already have type-casting functions: `DT[:, dt.str32(f.A)]`. I'm not sure what you want here

**Comment by pseudotensor** [comment]
Could you give example, by way of re-writing the above code?

**Comment by st-pasha** [comment]
I see, so you're asking to make it possible to specify a conversion which would raise errors rather than suppressing them. Although I'm not clear what should qualify as an "error" in the case of converting to string.

**Comment by pseudotensor** [comment]
Can't you have objects that aren't strings?

**Comment by st-pasha** [comment]
You can, but they happily get cast into strings by pandas:
```
>>> p0 = pd.DataFrame({"A": [1,2,3, 7.6, None, (3, 4), b"The End"]})
>>> p0.astype(str, errors="raise")
            A
0           1
1           2
2           3
3         7.6
4        None
5      (3, 4)
6  b'The End'
```

**Comment by pseudotensor** [comment]
So pandas can have crazy objects like other non-tabular objects, images, etc. Right?  I think the point of that code, @arnocandel can confirm, is for pandas or parquet inputs into DAI.

**Comment by pseudotensor** [comment]
@st-pasha , so could you write a code that does the same as the original version?  Thanks!

**Comment by st-pasha** [comment]
@pseudotensor 
When you ask `pandas` to convert a dataframe into 'str' type, pandas will apply `str(x)` for every value in the frame and collect the resulting string values. It is nearly impossible for this process to cause an error. In this example, I'm creating a pandas dataframe with all sorts of crazy stuff, and it still works:
```
>>> import datatable as dt
>>> import blessed
>>> import pandas as pd
>>> df = pd.DataFrame([pd, blessed.Terminal(), {"foo": 1}, pd.DataFrame([range(10)]), dt.Frame(range(10))])
>>> df.astype('str', errors="raise")
                                                   0
0  <module 'pandas' from '/Users/pasha/py36/lib/p...
1  <blessed.terminal.Terminal object at 0x103d4f080>
2                                         {'foo': 1}
3     0  1  2  3  4  5  6  7  8  9\n0  0  1  2  3...
4                          <Frame [10 rows x 1 col]>
```

The only way this may fail is if one of the entries contains an object with badly written `__str__` method (and I say badly written because technically this method is not supposed to throw exceptions):
```
>>> class A:
...   def __str__(self):
...     raise RuntimeError
... 
>>> df = pd.DataFrame([A()])
>>> df.astype('str', errors="raise")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pasha/py36/lib/python3.6/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/Users/pasha/py36/lib/python3.6/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/Users/pasha/py36/lib/python3.6/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/Users/pasha/py36/lib/python3.6/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/pasha/py36/lib/python3.6/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/Users/pasha/py36/lib/python3.6/site-packages/pandas/core/internals.py", line 625, in _astype
    values = astype_nansafe(values.ravel(), dtype, copy=True)
  File "/Users/pasha/py36/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 648, in astype_nansafe
    return lib.astype_unicode(arr.ravel()).reshape(arr.shape)
  File "pandas/_libs/lib.pyx", line 859, in pandas._libs.lib.astype_unicode
  File "pandas/_libs/lib.pyx", line 867, in pandas._libs.lib.astype_unicode
  File "<stdin>", line 3, in __str__
RuntimeError
```

The possibility that you will see this in any kind of real-life application is **extremely small**. But, for the sake of argument, let's suppose you got extremely unlucky and got yourself such a dataset. In this case, `pandas` gives you 2 options: `errors="ignore"`, which suppresses the exception and returns the original object unmodified; and `errors="raise"`, which raises an exception and allows you to drop the offending column. On the other hand, `datatable` has only 1 option, and that option will convert all values that caused exceptions into NAs. In my view, this is a much better alternative, as it minimizes the amount of information lost, while still assuring that the conversion was successful.

I'm not saying that there couldn't be situations where pandas modus operandi might be preferable, but I doubt your use case is among them.

**Comment by pseudotensor** [comment]
Ok, we can bisect.  Let's assume you are right.  Can you still write a code that does the above operation?  It needs to be per-column, not per-frame:

```
for c in tr.names:
        if tr[c].ltypes[0] == dt.ltype.obj:
                tr = set_dt_col(tr, c, tr[c].topandas().astype('str', errors='raise'))
```


Thanks.
