### ISSUE TITLE
Implement group-aware shift (lead/lag) function

### ISSUE THREAD

**Issue by atroiano** [h2oai/datatable#1513]
Ability to get lead and lag of variables based on groups and assign those values to a new column within the datatable, based on a naming convention, it should also allow for an elegant want to handle the first record for a lag or last record for a lead (default in the example below).

Example code could be something like - 
```df(select=lag(f.x), group="y",window = 3, name='lag', default = -1)```

The result would be a new column called x_lag_3 and contains the value 3 periods in the past for that given group.

**Comment by st-pasha** [comment]
I'm proposing the following API:
```
DT[:, shift(f.x, n=3, fill=-1), by(f.y)]
```
- The parentheses-call syntax is currently scheduled for deprecation, in the future we'd want to have `DT[i, j, ...]` only. The parentheses was the form that we had originally since day 1 of datatable, before we figured out how to make the square-bracket syntax work.
- Function name `shift` is used in R data.table, and also is more versatile because it encompasses both leads and lags. Name `shift` is also used in pandas.
- The `n` parameter is the amount of shift: positive `n` shifts forward (creating a "lag"), negative shifts backwards ("lead"). The default is `1`.
- The `fill` parameter specifies how to fill the missing values at the beginning/end of the column. The name "fill" is used by R data.table's `shift()`, and also by `fread()`. Your proposal was `default`, pandas doesn't have such parameter, and scipy has `cval`. In my view, `fill` is the most straightforward name of these all.
- The `name` parameter is not necessary, since the user can specify column names in the select expression itself.

One advantage of not having `window` parameter as an argument to `DT()` is that it becomes easy to use various shifts in a single expression (which is common):
```
DT[:, {"x_lag_1": shift(f.x, 1),
       "x_lag_2": shift(f.x, 2),
       "x_lag_3": shift(f.x, 3)}]
```

**Comment by atroiano** [comment]
How would I shift multiple columns multiple times without manually typing out the 
```shift(f.x,1)``` part, in this solution?   An example use case, I have ~300 different features that need to be lagged 16 different times.  It's unreasonable to have to type out all of those cases.  In pandas, I can do a loop and select the columns, in R, I can use dpylr (even though it's slow and a memory hog).

**Comment by st-pasha** [comment]
```
DT[:, {"%s_lag_%d" % (feature, period): shift(f[feature], n=period)
       for feature in features
       for period in range(1, 17)}]
```

**Comment by atroiano** [comment]
ahhh awesome

**Comment by hutaohutc** [comment]
> How would I shift multiple columns multiple times without manually typing out the
> `shift(f.x,1)` part, in this solution? An example use case, I have ~300 different features that need to be lagged 16 different times. It's unreasonable to have to type out all of those cases. In pandas, I can do a loop and select the columns, in R, I can use dpylr (even though it's slow and a memory hog).

@atroiano In R,you can also use data.table rather than dplyr like:

```
for(j in freture_old){
  for(i in 1:n ){
    data[,(paste0(j,"_",i)) := shift(.SD,i),.SDcols =j ]
  }
}
```
There is my test:
```
library(data.table)
data <- data.table(date = as.Date("2015-05-01")+0:299)
set.seed(123)
data[,":="(
   a = round(30*cumprod(1+rnorm(300,0.001,0.05)),2),
   b = rbinom(300,5000,0.8)
 )]

data

n = 3
freture_old <- c("a","b")

for(j in freture_old){
  for(i in 1:n ){
    data[,(paste0(j,"_",i)) := shift(.SD,i),.SDcols =j ]
  }
}

data
```

**Comment by hutaohutc** [comment]
@XiaomoWu can you provide an idea withou for loop ,just using `lapply` ?

**Comment by jangorecki** [comment]
@hutaohutc data.table `shift` is well vectorized, over columns, and over `n` arguments also, thus the following will work:
```r
data[, sapply(freture_old, paste, 1:n, sep="_") := shift(.SD, 1:n), .SDcols=freture_old]
```

**Comment by hutaohutc** [comment]
@jangorecki Thank you ,I didn't know the `n` argument is  vectorized ,thank you a lot !

**Comment by hutaohutc** [comment]
@jangorecki Thank you for your time,I would like to ask you  if I made a custom which is not vectorized in arguments `n` ,such as `add <- function(x,n) (x+n)` 

I can use for loop like this:
```
for(i in 1:n ){
  data[,(paste0(freture_old,"_",i)) := add(.SD,i),.SDcols =freture_old ]
}
```

Can l use a `lapply` function to instead the for loop?

Please don't mind if I asked a stupid question.
BTW, I'm very excetied when I know datatable can be used in python, thank you for you work.

**Comment by jangorecki** [comment]
This is not a proper place to ask such questions, best on stackoverflow. Yes lapply can be used instead of loop.

**Comment by hutaohutc** [comment]
thank you for your suggestion~
