### ISSUE TITLE
.replace() to work on columns

### ISSUE THREAD

**Issue by antorsae** [h2oai/datatable#1599]
Im a datatable noob so please bear with me:

I expected this to work, i.e. replace 2 into -2 just on column 'A'
```
>>> import datatable as dt
>>> DT = dt.DataTable({'A': range(0,10), 'B': range(0,10)})
>>> DT[:,'A'].replace(2,-2)
>>> DT
      A   B
---  --  --
 0    0   0
 1    1   1
 2    2   2
 3    3   3
 4    4   4
 5    5   5
 6    6   6
 7    7   7
 8    8   8
 9    9   9

[10 rows x 2 columns]
```

but it doesn't. How can I replace just on a column?

**Comment by st-pasha** [comment]
`DT[:, "A"]` selects column "A" from frame `DT`, and returns the result as a new frame, separate from the original `DT`. Then `.replace(2, -2)` modifies that new frame in-place, and the result disappears because it is not assigned to any variable.

Currently, `.replace()` works on the entire frame, there is no ability to apply it to a specific column. This is a new capability that should probably be added.

In the meanwhile, you can achieve the desired result through the following work-around:
```
col = DT[:, "A"]
col.replace(2, -2)
DT[:, "A"] = col
```
