### ISSUE TITLE
FR: Apply a slice to each string in a string column

### ISSUE THREAD

**Issue by wjensheng** [h2oai/datatable#1667]
Hi guys,

I wonder how can I implement the equivalent datatable function of doing the following in pandas dataframe?

`df[:,'col'] = df[:, 'col'][-8:]`

Basically, I am trying to parse all my `df['col']` to get the last 8 letters. But I am facing the error above. Surprisingly, the below code works but it takes too long.

```
for each_row in range(df_len):
	df[each_row, 2] = df[each_row, 2][-8:]
```
Thank you.

**Comment by wjensheng** [comment]
resolved. Thanks to Branden.

`df[:,2] = datatable.Frame([s[-8:] for s in df[:,2].to_list()[0]])`

**Comment by st-pasha** [comment]
Branden's work-around certainly works, but it involves converting the column into python list, which is something we'd prefer to avoid.
Re-opening this issue to implement functionality natively.

**Comment by wjensheng** [comment]
Hey @st-pasha it's summer holiday for me right now. I am interested in helping to contribute to the `datatable` library. Can you please provide some guidance in how and where to start? Thank you.

**Comment by st-pasha** [comment]
Hi @wjensheng, thank you for your interest.
If you're thinking about contributing this feature, then here's the high-level overview of where to start looking at:

- First, start by figuring out how the final API should look like. For example, string-splice could be a standalone function, or a method, or a square-bracket "getter". So, the first step is to think about which of these might be more natural/easier to use. 
For the sake of continuing discussion, let's suppose that we want the following code to work: `DT[:, f.name[:10]]`, which would take column "name" in frame `DT`, and produce a new column containing only first 10 chars in the name.

- Currently when you type `f.name[:10]`, you'll get an error: "TypeError: 'Expr' object is not subscriptable". So it means, you need to go into the `Expr` class (in file "datatable/expr/expr.py") and add the `__getitem__()` method. You'll notice that all methods in `Expr` are absolutely trivial, merely creating new `Expr` objects with a specific OpCode. So, you'd want to create a new OpCode for string slicing, and specify it in 2 enums: one in "expr.py" file, and another in "c/expr/expr.h".

- After you added the opcode, the next stop is file "c/expr/expr.cc" where the op starts getting resolved at runtime. You'll see the `factory` map there, which lists functions that are responsible for processing each Op. Since string-slicing is somewhat unlike any other function, you'll probably want to create a new `pexpr make_string_slice(Op, const py::otuple& args)` function there and declare it in `init_expr()`. Note that at this stage you will be converting python objects into C++ objects, so you may want to look at "c/python/*.h" files to see how we do it (in particular, slice.h will probably be useful).

- The function `make_string_slice` from the previous step is supposed to return a `pexpr` -- a unique_ptr to a class derived from `base_expr` (defined in "c/expr/expr.h"). It is this class that does most of the work. Naturally, this derived class has to be added first. Probably, it would be most at home when declared in "c/expr/expr_str.h". This class should override the following methods:
  - `resolve()`: must "resolve" all its arguments, then check their stypes (throw an error if the argument's type is wrong), then return the stype of the result.
  - `get_groupby_mode()`: for a 1-to-1 mapping like your function, this should just return the same result as the argument's get_groupby_mode
  - `evaluate_eager()`: this is where the result column will be constructed. The input is a `workframe` (see "c/expr/workframe.h"), but for you this object is barely needed. What's needed is to run `arg->evaluate_eager(wf)` to obtain the "argument" column. This column will have "string" type (assuming  you checked the types in the resolve step). It's a base `Column` object, but you can dynamic-cast it into `StringColumn<T>*` (where `T` is either `uint32_t` or `uint64_t`). Both `Column` and `StringColumn` classes are defined in `c/column.h`. In order to create a new (output) string column, the standard method is `map_str2str(input_col, func)` defined in "parallel/string_utils.h". The second argument there is a "mapper" function of the form `void(size_t j, CString str, string_buf* sb)`, where the first argument `j` is the index of the entry (could be -1 if entry is missing), the second argument `str` is the string itself at position `j` in the input column (CString is just a pointer+size struct), and the last argument is the "writer" where you want to "submit" the results. This class is defined in "wstringcol.h", class `writable_string_col::buffer`. In your case the `prepare_raw_write()/commit_raw_write()` would probably be the most efficient methods to use.

**Comment by Peter-Pasta** [comment]
Hi, I am also very interested in this feature. Is this included in the 0.11.0 release and I missed it or something slated to come out in later versions?

**Comment by st-pasha** [comment]
It wasn't implemented yet, but we hope to get it into the next release.

**Comment by Peter-Pasta** [comment]
Thank you for letting me know. The additions in version 0.11.0 are already great! I really appreciate the hard work you are putting into datatable.

**Comment by pradkrish** [comment]
@st-pasha I am interested in giving this one a go. Is the high-level overview you have written above still valid? I see that a lot has changed since then. It will be really useful if you can update the content above, I am just wondering how to get started. :thinking:

**Comment by st-pasha** [comment]
@pradkrish Thanks for your interest. The up-to-date description of how to add new functionality is [here](https://datatable.readthedocs.io/en/latest/develop/create-fexpr.html). It is not too different from what's outlined above, though we have `FExpr`s now instead of `Expr`s.

If you want to add functionality as a simple function, such as `dt.str.slice()`, then the documentation linked above has all the necessary information (including the "Submodules" section). However, if you want the slice syntax to work, then it would take some more work:
  - add method `oobj m__getitem__(robj item);` into  the class `PyFExpr` declared in "expr/fexpr.h";
  - register this method from `void PyFExpr::impl_init_type(XTypeMaker&)` (in file "expr/fexpr.cc"). Registering is just a single line `xt.add(METHOD__GETITEM__(&PyFExpr::m__getitem__));`;
  - implement the method in any file you want, following the examples from the documentation.

**Comment by st-pasha** [comment]
Hi @pradkrish -- did you have a chance to start working on this yet?

I'm only asking because this is one of the few remaining issues assigned to [Release 1.0](https://github.com/h2oai/datatable/milestone/24) milestone, and we want to make the release by the end of the month. So if you haven't started, I'd like to take this over and implement this FR.

**Comment by pradkrish** [comment]
@st-pasha I got started with this briefly, check out this branch `pk/fexpr_slice`. I am busy with deadlines at my work currently, kindly go ahead and take over. I am very happy to have this feature implemented. Thanks.
