### ISSUE TITLE
Enhancement of using-datatable.rst documentation. Add importing operator "by", "sort", examples, etc.

### ISSUE THREAD

**Issue by Viktor-Demin** [h2oai/datatable#1699]
```
import datatable as dt
from datatable import f, min, max,mean
import math
DT1 = dt.Frame(A=range(5), B=[1.7, 3.4, 0, None, -math.inf], C = [1,1,1,2,2],
               stypes={"A": dt.int64})


DT1[:,mean(f.A),by(f.C)]
```

Returns:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-62-1e6b6dedb0de> in <module>()
      6 
      7 
----> 8 DT1[:,mean(f.A),by(f.C)]
      9 

NameError: name 'by' is not defined
```

version 0.8.0

**Comment by oleksiyskononenko** [comment]
@Cheburusska one should also import `by`, then it will work:

```
>>> import datatable as dt
>>> from datatable import f, min, max, mean, **by**
>>> import math
>>> DT1 = dt.Frame(A=range(5), B=[1.7, 3.4, 0, None, -math.inf], C = [1,1,1,2,2],
...                stypes={"A": dt.int64})
>>> 
>>> 
>>> DT1[:,mean(f.A),by(f.C)]
      C   C0
---  --  ---
 0    1  1  
 1    2  3.5

[2 rows x 2 columns]
```

**Comment by Cheburusska** [comment]
@oleksiyskononenko you are very right and now it works. I believe it is worth to add in documentation to avoid confusing. I would to do it myself and contribute to this project. Do we have any manual for that?

**Comment by oleksiyskononenko** [comment]
@Cheburusska Sure, here is the [manual](https://datatable.readthedocs.io/en/latest/?badge=latest), and this is the [groupby](https://datatable.readthedocs.io/en/latest/quick-start.html#by) section under `Getting started` that already has this info. 

Guess the source of confusion is that there is also `Using datatable` section (that is the older version of `Getting started`) that may not be that detailed. The idea was to move all the items from `Using datatable` to `Getting started` making them as detailed as possible. This is now WIP, and you are welcome to contribute, of course.

**Comment by st-pasha** [comment]
Hi @Cheburusska, thank you for your feedback.
After using the `datatable` for a while, importing these symbols becomes almost a second nature. Which is why it's so easy to forget to write about it in the documentation. So I absolutely agree that this is something that should be added.

As for where to add this info, I imagine this can be done in several places:
  - Mentioned somewhere at the top of "Using datatable" doc, or even right there in the groupby section;
  - On a special page "Guide for R data.table users", which would outline small things that an R user must watch out for when going into Python (such as importing names: R does it automatically, in Python you need to be explicit);
  - On a special page "Common problems" where a user can simply search for their error message and see how to resolve it;
  - On Stack Overflow -- questions on SO are even easier to search, and easier to post too :) So if you posted exact same question on SO, and Oleksiy the same answer, then other people would have a high chance of finding it in the future.

If you're asking how to contribute to documentation, then the process is not too hard:
  - clone this repository;
  - go into the Docs folder and edit existing .rst files or create new ones (the docs for Restructured Text can be easily [found online](http://docutils.sourceforge.net/docs/user/rst/quickref.html))
  - run `make html` to convert rst into html, then view file "docs/_build/html/index.html" in a browser to verify that it looks as you think it should;
  - commit your changes and make a Pull Request.

**Comment by Cheburusska** [comment]
@oleksiyskononenko @st-pasha thank you for detailed answer. Will start to work on documentation

**Comment by Cheburusska** [comment]
@st-pasha I'm working on documentation and decided implement ipython directive which allows automatically calculate during building like it works in pandas project.
But datatable returns strange results. What is the rootcause, can this be fixed?

```
.. ipython:: python

    import numpy as np
    import pandas as pd
    s = pd.Series([1, 3, 5, np.nan, 6, 8])
    s


.. ipython:: python

  import math
  DT = dt.Frame(A=range(5), B=[1.7, 3.4, 0, None, -math.inf],
                 stypes={"A": dt.int64})
  DT
```

![screen shot 2019-03-08 at 17 42 06](https://user-images.githubusercontent.com/19714042/54035159-c3c1ca00-41c9-11e9-9ede-0dcb3ac77336.png)

**Comment by Cheburusska** [comment]
@st-pasha but it works ok if use jupyter notebook instead of .rst files. If you don't mind I'll try to prepare quick-start from .ipynb

**Comment by st-pasha** [comment]
I've never tried writing a sphinx extension, but I agree that it would be cool if the code was executed when documentation is built.

Currently we only have set up the stylesheets so that the documentation pages would LOOK like they were taken from Jupyter notebook. However, the .rst code underneath looks like this:
```
```

**Comment by Cheburusska** [comment]
@st-pasha I believe that automatic calculation is much better that hardcoded raw html. Beside it is very simple to implement just need to add new directive in conf.py. But there is only problem with representing calculation of datatable.

Here is a source code:

```
.. ipython:: python

    x = 2
    x**3

.. ipython:: python

    import datatable as dt
    import math
    DT = dt.Frame(A=range(5), B=[1.7, 3.4, 0, None, -math.inf],
                     stypes={"A": dt.int64})
    DT

.. ipython:: python

    import pandas as pd
    pd.DataFrame({"A": range(3)})
```

and this is how it rendered after make html (in attached pdf)

![Screen Shot 2019-03-09 at 10 06 52](https://user-images.githubusercontent.com/19714042/54067626-417de800-4253-11e9-9fa0-7e6c687b4f9d.png)

[test_ipynb_directive — datatable 0.8.0 documentation.pdf](https://github.com/h2oai/datatable/files/2948144/test_ipynb_directive.datatable.0.8.0.documentation.pdf)

Because I believe that hardcoding is not very good I can see 2 options for doc building:

1) Discover and fix why datatable rendered this way in sphinx and I am my skills not yet enough for this so this should be done by you. But we can use very rich .rst format

2) use jupyter notebooks where we have demos of datatable. Because it renders datatable very well. But jupyter markdown is not so rich as rst. Please look in attached pdf. Also this can be option until option 1 is fixed.  [Tutorial — datatable 0.8.0 documentation.pdf](https://github.com/h2oai/datatable/files/2948163/Tutorial.datatable.0.8.0.documentation.pdf)

Please give your perspective because it is very time consuming

I would definitely vote for option 2 because option 1 can take a lot of time. And jupyter notebook still looks very good .

Pasha you see it at my fork:
https://github.com/Cheburusska/datatable

**Comment by Cheburusska** [comment]
@st-pasha I investigated and found out that building from notebooks also very powerful. It support html and ``DT``. So I think there are no cons of using notebooks for parts of documentation with calculations and examples.

**Comment by Cheburusska** [comment]
@st-pasha I opened merge request, please look into this

**Comment by st-pasha** [comment]
@Cheburusska When we were writing documentation, we considered several approaches for how to do that, but none of them worked out of the box quite the way it should. Which is honestly quite frustrating given that the task of maintaining documentation is so common.

Originally, Python documentation was built on top of the ReStructured Text format (.rst), which is just plain text with minimal amount of markup to denote various structural elements. It is nicely extensible too, and supports flexible inter-project linking. Standard tools such as `sphinx` exist in order to compile rst files into HTML, PDF or any other output format.

On the contrary, Jupyter notebooks were designed for interactive work, not for documentation. Surely, there are tools now that allow a programmer to convert a notebook into HTML/PDF and then use that output for the documentation; and I've even seen projects that adopt such approach. However, IMHO such approach is worse compared to .rst files for several reasons:
  - .rst files are human-readable (a reasonable person can easily read/edit .rst files), whereas .ipynb files are much more difficult to understand without a specialized viewer;
  - .rst files are Source Control -friendly. That is, if someone needs to change a documentation file, then with .rst files all changes will be localized and easy to review with standard diff tools. With .ipynb files a single change in one cell may cause a huge diff with all other cells being updated too (and in general reviewing a diff in .ipynb file is very challenging);
  - .ipynb files are not stable: the act of rendering documentation will cause the file to be executed, which may change its content. Ideally we don't want such changes committed into the repo;
  - .rst files are easier to edit in a code editor, because they are plain text files. 

**As such, I feel that having documentation in .ipynb format will cause too much frustration from the standpoint of long-term support.**

The ideal solution would be to find (or write) a sphinx extension that would run during the generation of HTML target, and for each AST node of type "python" it would evaluate its content, style it as an "output" code block, and if the return value is an object, attempt to call the standard `._repr_html_()` function on that object. That way we wouldn't have to hard-code any of the results.

A slightly less ideal, but much more simple approach is to write a side-along script that would manually scan each .rst file, find all blocks that begin with `::`, execute them, and then compare those blocks against the corresponding output block in the same file. That way the results will still have to be hard-coded, but at least we will have a guarantee that the results always remain correct.

**Comment by Cheburusska** [comment]
@st-pasha I can see that pandas, statsmodels, patsy, etc. are using [ipython directive](http://ipython.org/ipython-doc/3/api/generated/IPython.sphinxext.ipython_directive.html).

If use this directive with datatable than corrupted results generated:

![image](https://user-images.githubusercontent.com/19714042/54142993-e9550a80-4439-11e9-978b-c8f237d0c79f.png)


I [raised issue](https://github.com/ipython/ipython/issues/11643)  but don't think there will be result soon. Maybe you can advice how to investigate this bug or you can look into this?

Because I look on documentation from user stand point and can see that hardcoding creates a lot of confusing which can be avoided if all examples calculated during building as it is done in ipython directive or if use jupyter notebook.

**Comment by Cheburusska** [comment]
@st-pasha do you know if colour coding can be turned off in jupyter notebook for datatable? It is the rootcause of corrupted rendering. https://github.com/ipython/ipython/issues/11424#issuecomment-471988845

**Comment by st-pasha** [comment]
Importing of `by`, `sort`, etc is already mentioned in quick-start
