### ISSUE TITLE
Assigning of new or reassigning existing columns in j part, similar to ':=' operator in R data.table

### ISSUE THREAD

**Issue by Viktor-Demin** [h2oai/datatable#1700]
Please implement assigning new or existing columns.

This is how it works in R data.table:
`DT[,X := A+B, by = .(y,z)]`
and multiple assigning
`DT[, ':=' (X = A+B, k = A/B), by = .(y,z)]`

**Comment by st-pasha** [comment]
Column assignment is currently possible, although not by group:
```
>>> import datatable as dt
>>> from datatable import f, by
>>> DT = dt.Frame(A=range(5), B=range(10, 20, 2))
>>> DT[:, "X"] = f.A + f.B
>>> DT
     A   B   X
--  --  --  --
 0   0  10  10
 1   1  12  13
 2   2  14  16
 3   3  16  19
 4   4  18  22

[5 rows x 3 columns]

>>> DT[:, "Y", by("A")] = f.A + f.B
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NotImplementedError: exprlist_rn::replace_values()
```
Thus this issue is similar to #1312 in terms of implementation.

**Comment by XiaomoWu** [comment]
@st-pasha sure `DT[:, "X"] = f.A + f.B` works, but the good thing by puting the assignment expression in `j` is that we can chaining multiple `dt[i,j,by]` expression together. Besides, compared with the argubaly cumbersome  `dataframe` way `DT[:, "X"] = f.A + f.B`,  `dt[, f.a := f.b + f.c]` is more coherent and elegant.

**Comment by Cheburusska** [comment]
@st-pasha I fully agree with @XiaomoWu, beside assignment in j is very user friendly and very good for people who comes from R. Do you have plans on this? 
2) Why do you use f.? in R data.table there is no such operator and it works very good 
3) Is there way to omit using "" like in R data.table?  DT[:,X] instead of DT[:,"X"]

**Comment by st-pasha** [comment]
@Cheburusska @XiaomoWu 

> Do you have plans on this?

Yes, we had a general discussion about this in https://github.com/h2oai/datatable/issues/1187 and decided to implement an `update()` function which could be used in `j` place. However, it has not been implemented yet.

> Is there way to omit using "" like in R data.table? DT[:,X] instead of DT[:,"X"]

Unfortunately, no. In Python any bareword such as `X` must refer to an existing variable. R is much more flexible with its syntax in this regard. Which is why we came up with the `f.X` syntax, which is not as clean-looking, but gets the job done. It also comes with a few additional benefits:
- easy to access a column by variable name: `f[var]` (in R it's `..var`, which is a relatively new addition), or even by expression: `f[prefix + "_" + str(n)]`;
- columns can also be accessed via their index in addition to a name: `f[3]`;
- joined frame uses prefix `g.`, so it is always clear where the column comes from (in R you can say `i.X` or `x.X`, which arguably similar to `f.X/g.X`).

Also, if the visual clutter of `f.X` is unbearable, you can always define in advance at the top of your script that `X = f.X`. Then the variable `X` can be used as-is in a DT expression: `DT[:, X * 2]`.
