### ISSUE TITLE
"datatable.TypeError: Boolean value cannot be used as an` i` expression" when `i` expression is set to "[...is not None, :]"

### ISSUE THREAD

**Issue by navdeep-G** [h2oai/datatable#1781]
It seems having the row filter with set to `[... is not None, :]` causes the exception: 
```
Boolean value cannot be used as an` i` expression
```
However, the exception is not hit when the row filter is set to `[... != None, :]`

- How to reproduce the bug?
```
import datatable as dt
from datatable import f

fr =  dt.Frame(np.random.randn(1000000))   
fr[f.C0 is not None, :]  
```

- Your environment?
      - datatable version: `0.8.0.dev7`, 
      - python version: `3.6.2`
      - operating system: `Ubuntu 16.04`

**Comment by st-pasha** [comment]
This is not a bug, it's a peculiarity of Python language.

In python `is` and `is not` operators are not overloadable, hence `f.C0 is not None` will trivially be `True` since `f.C0` is an object (a column-selector expression), and that object is not same as builtin object `None`. Thus, python performs this computation and then calls `fr[True, :]`. At this point `datatable` has no idea where that `True` came from, it just knows that it's likely an error on user's part, and this is why it throws an error.

We chose to `fr[True, :]` to be an error (rather than returning all rows as R data.table does) specifically because it is very easy to create this expression accidentally.

The expression `fr[f.C0 != None, :]` is perfectly valid, however, since `==` and `!=` can be overloaded in python, and thus `datatable` treats `f.C0!=None` as a column expression which is the result of comparing each element in column `f.C0` against value `None`.
