### ISSUE TITLE
String function not applicable when `f.x` is a `str`

### ISSUE THREAD

**Issue by XiaomoWu** [h2oai/datatable#1839]
First, thanks for your great work to bring `datatable` to python. My questions is that currently, `f.x` can't be used "as if" a `str` in a string function. For example:

```
df = dt.Frame(x=['a','b','c'])
df[:, ''.join([f.x, 'bbb'])] # fail
df[:, f.x+'bbb'] # fail
```
Both report error like `expected str instance, ColSelectorExpr found`.

This behavior is similar to #1667. The key here is that `f.x` is interpreted as a `ColSelectorExpr` instead of a `str`. Of course, we might invent "ad-hoc" functions to bypass this (e.g. #1689), however, I'm wondering if there exists a way to interpret `f.x` just as a `str` in all `str` functions?

**Comment by XiaomoWu** [comment]
Ok, I find it's in the Roadmap #290. Any plan to deliver the feature in the near future?

**Comment by st-pasha** [comment]
Most string functions in python are actually methods of class `str`, for example: `"ABC".lower()`. As such, it is possible to implement same methods for `f.x` when it is of string type. Thus, it is possible to make `f.x.lower()` work. The `"".join(...)` is slightly different in this case, because it is applied to the separator string rather than to the collection being joined. Thus, `"".join(f.x)` would not work, because python `str.join()` method does not know anything about datatable. But we could provide a similarly-named method that uses a different argument order, for example `f.x.joinall("")`. The operator version can be implemented too: both `f.x + "bbb"` and `"aaa" + f.x`.
