### ISSUE TITLE
[segfault] assigning dtFrame.key before join crashes

### ISSUE THREAD

**Issue by goldentom42** [h2oai/datatable#1870]
Hi,

Datatable version 0.8.0, happens on both linux and OSX
python version 3.7.1 on OSX and 3.6.7 on linux

I need to join 2 frames on 2 keys, but got `segmentation fault` when assigning frame `key`.

Simple way to reproduce:
```
import numpy as np
import datatable as dt

X_dt = dt.fread("monthly.csv.zip", max_nrows=1000000)

time_column = "the_date"
tgc = ["the_date", "shop_id", "item_id"]
tgc_wo_time = list(np.setdiff1d(tgc, time_column))

X_dt[:, "y"] = X_dt[:, "item_cnt_day"]

group_means = X_dt[:, dt.mean(dt.f.y), dt.by(*tgc_wo_time)]

# This is the segfault line
group_means.key = ("shop_id", "item_id")

```

File `monthly.csv.zip` is available here ->

https://drive.google.com/open?id=165ozuYXDevM7UYDVMPkxJoQ6lsU8GjQP

limiting the fread to `max_nrows=100_000` makes the code pass, so it seems there are too many keys with `max_nrows=1_000_000`.

**Comment by goldentom42** [comment]
Does not seem to happen with datatable-0.8.0.dev71 .

**Comment by st-pasha** [comment]
Thank you Tom, for filing this report. 
As you correctly note, this problem exists in 0.8.0, yet the code works correctly in the latest dev version. In fact, this is likely to have been fixed in https://github.com/h2oai/datatable/pull/1645, quite some time ago. We are planning to release 0.9.0 in the near future (within a month or so), which will include fixes to this and many other bugs.
