### ISSUE TITLE
[bug] calling dt_df.head() second time does not show color to indicate datatypes

### ISSUE THREAD

**Issue by zawrahman** [h2oai/datatable#1871]
- Did you find a bug in datatable, or maybe the bug found you?
Running `dt_df.head()` second time on a cell in Jupyter doesn't show the datatype colors 

- How to reproduce the bug?
To reproduce the results:
`dt_df = dt.fread('sample.csv')`
`dt_df.head()`
will produce correct outcome, but rerun the `dt_df.head()` will not show datatype colors anymore.
- Your environment?
Using jupyter lab latest version on python 3.6 and datatable version 0.8.0

**Comment by st-pasha** [comment]
I was able to reproduce the first bug: the issue seems to be that we emit datatable stylesheet the first time a frame is rendered, but not on subsequent calls. When a frame is re-rendered, the previous CSS gets erased by Jupyter.

It is not clear what the best solution would be.
 - emitting CSS with _every_ rendered frame will work, but will result in a bloated size of the notebook;
 - emitting CSS with `import datatable` will work, provided this statement is not re-run later;
 - add an explicit function, such as `dt.init_jupyter()`, that must be called by the user after import.

I will also need to check whether Jupyter itself provides any utilities to tackle this problem.

**Comment by st-pasha** [comment]
As for `df.head()` function, the default value of `n` is 10. This is what the help says:
```
head(self, n=10) method of datatable.Frame instance
    Return the first `n` rows of the frame, same as ``self[:n, :]``.
```
So I'm not sure why you think that the default was 5. The behavior of `DT.head()` and `DT.head(10)` is exactly the same, as it supposed to be.

**Comment by zawrahman** [comment]
You are right, I see the documentation now. I edit my report. Thanks
