### ISSUE TITLE
Development version numbering

### ISSUE THREAD

**Issue by jangorecki** [h2oai/datatable#1976]
Currently in my python session, having installed from devel, I am getting
```
dt.__version__
'0.10.0'
```
thus I could expect issues assigned to 0.10.0 milestone to be resolved.
But it happens that 0.10.0 is still on-going dev.
I propose to make distinction in version numbers between stable and devel.
In R dt we use even numbers for stable, odd for devel. Many R packages uses 0.9.0.9999 as devel version to be 0.10.0 stable.
Any of this would be better than current ambiguous numbers.

An example possible use case. One might want to branch code based on new feature added in 0.10.0
```
if (version >= "0.10.0") do_new_stuff() else do_old_stuff()
```
Such code would break if user had installed devel version.

**Comment by jangorecki** [comment]
I think it make sense to stick to python-way of doing that, so using `a` suffix

**Comment by jangorecki** [comment]
I don't think we need to be as much detailed when providing version, there is another field that has commit hash, it gives ultimate precision.

**Comment by mmalohlava** [comment]
Regarding suffix - i think it is good idea to keep that in the repo - kind of `-SNAPSHOT` mark from Java-world

Regarding local build - we are using similar pattern with `user` and git hash in DAI - it is quite useful for testing

Note: 
  - I just would like to make sure that we can uniquely identify artifacts, which are produced by CI (main branch, nightly, PRs), and local artifacts 
  - as @st-pasha mentioned original design was based on PEP-440, so i would keep building on top of that (not perfect, since it has limitations, but we are trying to adopt it cross different projects as a baseline).
