### ISSUE TITLE
Need to keep pandas types when creating a datatable frame

### ISSUE THREAD

**Issue by achraf-mer** [h2oai/datatable#2092]
Here is a description in code on how to reproduce:

```python
import pandas as pd
import numpy as np
import datatable as dt

def new_pd():
    columns = [('c1', str), ('c2', str)]
    series = [pd.Series(dtype=t, name=c) for c, t in columns]
    return pd.concat(series, axis=1)
```

the above should will return a pandas array with object types (aka str), now considering this:
```python
df1 = new_pd().append({'c1': 'foo', 'c2': 'bar'}, ignore_index=True)
dt1 = dt.Frame(df1)
print(dt1.stypes)

df2 = new_pd().append({'c1': 'foo', 'c2': np.nan}, ignore_index=True)
dt2 = dt.Frame(df2)
print(dt2.stypes)
```

I get this response:
```
(stype.str32, stype.str32)
(stype.str32, stype.bool8)
```
Notice the `stype.bool8` when only have one row with a nan, this I believe need to be changed to return the same result as dt1, which is `stype.str32`.

The current workaround is to look back at each column series and modify its type to accommodate the pandas type.
Open to suggestions/corrections.

**Comment by st-pasha** [comment]
The pandas frames in your example all have dtype "object":
```
>>> df1.dtypes
c1    object
c2    object
dtype: object
>>> df2.dtypes
c1    object
c2    object
dtype: object
```

In this case "preserving types" would imply that we need to create a Frame with stypes `obj64`, which is, frankly, not very useful. A column with type `obj64` suffers a number of drawbacks: (1) it can only be processed by Python functions, which is slow, (2) it can only be processed in a single thread, (3) it cannot be saved into Jay or CSV format, (4) support for this stype is currently limited. In fact, the "object" type is so problematic that Arrow doesn't support it at all.

And the only reason that Pandas have "object" type is because they don't have type "string". So, in order to account for this calamity, whenever we see a pandas column of type "object", we run that column through a type resolver, which attempts to convert the object column into a more sensible type. So if a column contains only a single NA value, the smallest type that we can guess is `bool8`.

In theory, we could have created a special `void` stype to account for columns containing only NA values (e.g. there is such type in h2o-3), but that may require quite a lot of changes.

**Comment by arnocandel** [comment]
the problem arises when we want to join that column later and the join key has to wrong type, when it should be a string.

**Comment by achraf-mer** [comment]
Issue was mainly during the join operation on two frames with a column mismatch.
@st-pasha what you mentioned make sense, this might require lot's of changes, will close for now and feel free to reopen if needed.
