### ISSUE TITLE
to_csv(header=False, mode="a") support?

### ISSUE THREAD

**Issue by junghoocho** [h2oai/datatable#2130]
It will be great if there is a way (1) to disable writing the header line and (2) to append to an existing file.

Due to the lack of such support, whenever I need to do it, I write the csv output to a string first, remove the header line myself, and append the string to a file. Having the above two options will make this so much easier and natural. 

Thank you!

**Comment by st-pasha** [comment]
Sounds like a great idea! Though instead of `mode="a"` it might be simpler to say `append=True` (since only 2 file opening modes are sensible in our case: "a" and "w"). Then the `header=` option can accept either `True` or `False`, but defaults to `not append` if it is not given. Thus, the append mode would imply no headers by default, unless the user explicitly requests them.

**Comment by junghoocho** [comment]
That will be great! Thank you.

**Comment by st-pasha** [comment]
On further thought, I think an even better default to `header=` option is `not(append and os.path.exists(path))`. That is, if I say `DT.to_csv("out.csv", append=True)` then the headers will be written if the file does not exist, and not written if it does.

**Comment by junghoocho** [comment]
I completely agree.

In general, the `header` parameter should take three values, `True`, `False`, and `auto`. Then the default value should be auto, which means `not(append and os.path.exists(path))` and could be changed by setting `header` to `True` or `False` explicitly.
