### ISSUE TITLE
isna not applied correctly across elements of a dataframe generated from a numpy array

### ISSUE THREAD

**Issue by small-yellow-duck** [h2oai/datatable#2202]
dt.isna works when applied to individual float values from a dataframe, but not when broadcast across all the values in the dataframe

```
import datatable as dt
import numpy as np
np.random.seed(1)
X = dt.Frame(np.random.randn(5, 2))
print(X) #random floats
print(dt.isna(X[3, 0]) ) #ok, that's False
print(dt.isna(X) ) # this is some random-looking floats instead of all 0's
```

Perhaps this is related to https://github.com/h2oai/datatable/issues/2109 ?

**Comment by st-pasha** [comment]
Running your example, I'm getting
```
>>> dt.isna(X)
   | C0  C1
-- + --  --
 0 |  0   0
 1 |  0   0
 2 |  0   0
 3 |  0   0
 4 |  0   0

[5 rows x 2 columns]
```
Could you please check which version of datatable you have installed: variables
```
dt.__version__
dt.__git_revision__
```

**Comment by small-yellow-duck** [comment]
In [71]: dt.__version__
Out[71]: '0.9.0'
In [72]: dt.__git_revision__
Out[72]: '6cdfbce1ce8daa6d4d1612b1f6ff73442ea21af9'

**Comment by st-pasha** [comment]
Thanks, I was able to reproduce the bug on that version of datatable:
```
>>> dt.isna(X)
          C0        C1
--  --------  --------
 0  5.0751    0.542397
 1  0.589682  0.341992
 2  2.37597   0.100105
 3  5.72482   0.467102
 4  1.37581   0.779291

[5 rows x 2 columns]
```
At the same time, the following syntax worked correctly even then:
```
>>> X[:, [dt.isna(f[0]), dt.isna(f[1])]]
    C0  C1
--  --  --
 0   0   0
 1   0   0
 2   0   0
 3   0   0
 4   0   0

[5 rows x 2 columns]
```

In summary, it seems that (a) this bug did exist before, but was already fixed since then; (b) in order to get the correct behavior you could either switch to a newer version of datatable, or use the square-bracket syntax, which is more verbose in this case but at least gets the job done.

Sorry for the inconvenience. 
I'm not sure there's anything else I can do here, since the bug has already been fixed.
