### ISSUE TITLE
Why Buffer class overloaded move assignment operator not release its own old imlp_ object?

### ISSUE THREAD

**Issue by chi2liu** [h2oai/datatable#2410]
In the implementation of the Buffer class overloaded move assignment operator, why not release its own imlp_ object（Maybe it is just to reduce its refcount）, but simply exchange impl_ with other objects? impl_ here may not be nullptr.

https://github.com/h2oai/datatable/blob/master/src/core/buffer.cc#L655
`Buffer& Buffer::operator=(Buffer&& other) {`
`    std::swap(impl_, other.impl_);`
`    return *this;`
`  }`

In the implementation of the overloaded move assignment operator of the column class, not only the other impl_ is set to nullptr, but also the original impl_ object is released. I think this is the correct way. 

https://github.com/h2oai/datatable/blob/master/src/core/column.cc#L77
`Column& Column::operator=(Column&& other) noexcept {`
`  auto old = impl_;`
`  impl_ = other.impl_;`
`  other.impl_ = nullptr;`
`  _release_impl(old);`
`  return *this;`
`}`

Is the implementation in the Buffer class a bug? Or for other considerations? Hope to give answers and replies, and appreciate your reading and answers.

**Comment by st-pasha** [comment]
For a move-assignment operator, the starting point is that both `this` and `other` are fully-constructed objects. In `Buffer`'s case each of those objects owns its own `impl_` pointer. When we do `std::swap`, those pointers (and their ownership) is exchanged between two classes. Which means `this` now owns `other`'s `impl_`, and `other` now owns `this`'s `impl_`. Each pointer still has an owner class: no leaks occurred. 

Now, because `other` has been passed as an rvalue reference (`&&`), it means it is either a temporary or a "moved" variable, in either case it is about to die. And as it dies, it will destroy its `impl_` too, which was the old `this->impl_`.

The `Column`'s move-assignment works in a similar way, only it destroys the old `impl_` explicitly, without relying on `other`'s destructor. Both solutions are fine and correct. The Buffer's approach is more concise but more cryptic.
