### ISSUE TITLE
Zero raised to the negative power results in -2147483648

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#2587]
```
>>> from datatable import dt, f, math
>>> DT = dt.Frame([[0], [-1]])
>>> DT[:, f[0] ** f[1]]
   |          C0
-- + -----------
 0 | -2147483648

[1 row x 1 column]
```

At the same time the result is correct when a scalar or `math` module are used
```
>>> DT[:, f[0] ** -1]
   |  C0
-- + ---
 0 | inf

[1 row x 1 column]
>>> DT[:, math.pow(f[0], f[1])]
   |  C0
-- + ---
 0 | inf

[1 row x 1 column]
```

**Comment by st-pasha** [comment]
I think we should generally promote `[bool8|int8|int16|int32|int64] ** [bool8|int8|int16|int32|int65] => float64`

**Comment by st-pasha** [comment]
Low priority because raising numbers to a non-constant power is an extremely rare operation

**Comment by oleksiyskononenko** [comment]
May be if one of the arguments is `bool8` we can keep it as we do now, i.e. `common_stype(stype1, stype2)`.

**Comment by st-pasha** [comment]
Does raising booleans into any power occur in real life though?

**Comment by oleksiyskononenko** [comment]
Not sure, but It could also be something raised to the boolean power.

**Comment by pradkrish** [comment]
@oleksiyskononenko Taking the boolean raised to any power contrived example one step further, you will run into the same problem for `DT = dt.Frame([[False], [-True]])`. You get -2147483648 when you do `DT[:, f[0] ** f[1]]`. Promoting all output to `float64` regardless of the input datatype seems to be the way to go.

**Comment by st-pasha** [comment]
The only example that i know is the likelihood function for the logistic regression (http://www.stat.cmu.edu/~cshalizi/uADA/12/lectures/ch12.pdf), but even there the desired type is still float64.

**Comment by pradkrish** [comment]
After giving a cursory glance to why some tests failed, previously `str32|str64|obj64` ** `int32` would have thrown Typeerror but with the changes on this commit, it results in `float64` and hence the tests failed. Shall we do `common_stype(stype1, stype2)` if at least one of the arguments is `str32|str64|obj64` and `float64` for all other cases?

**Comment by oleksiyskononenko** [comment]
@pradkrish yes, but if it is anything raised to the boolean power, then there is no problem in leaving the type as is.

**Comment by pradkrish** [comment]
@oleksiyskononenko Thanks for the clarification, any thoughts on my follow up question regarding `str32|str64|obj64` ** `int32` ... ?

**Comment by st-pasha** [comment]
@pradkrish 
- `obj64` is the "object" stype, where the data stored in the column are regular python objects. It is highest in the hierarchy because anything can be a python object, but at the same time it is least useful. It is equivalent to numpy's `dtype('O')`.

- `common_stype(stype1, stype2)` function finds the smallest stype into which both `stype1` and `stype2` can be upcasted. For example, bool can be upcasted into int, which can be upcasted into float, which can be upcasted into str, which can be upcasted into obj.

- `string ** int` kinda doesn't make sense, so the tests are correct that a TypeError should be thrown. I guess the simplest way would be to compute common_stype, and then in the switch make all bool/int/float cases fall through into a single float64 case (except for float32, which must produce a float32 result). Then all other stypes would be the `default:` case which would result in a type error.

Please also bear in mind that the set of stypes is open, in the sense that we will be adding new stypes in the near future, so it's always good to be asking yourself what would happen if a new unexpected stype comes along into the function: it should throw some kind of error, but it definitely shouldn't crash.

**Comment by pradkrish** [comment]
@st-pasha Thanks for that, I was thinking exactly along the same lines.
