### ISSUE TITLE
[bug] Parsing error with fread

### ISSUE THREAD

**Issue by Darel13712** [h2oai/datatable#2680]
## Problem 

I get error reading csv with 0.11.0 datatable.

```
IOError: Too few fields on line 9811: expected 3 but found only 2 (with sep='t'). Set fill=True to ignore this error.  <<51372t"Great Performances" Cats (1998)tMusical>>
```
Well, I see 2 tabs there, and it works on all the other rows correctly. And it works with `datatable==0.10.1` just fine

## Steps to reproduce
[movies.dat.zip](https://github.com/h2oai/datatable/files/5333687/movies.dat.zip)
```
import datatable as dt
df = dt.fread('movies.dat')
```

## Environment
`Ubuntu 18.04.5 LTS, python 3.7.7, datatable==0.11.0`

**Comment by samukweku** [comment]
@st-pasha @oleksiyskononenko I had a look at the file that @Darel13712 shared; I cant see why it is returning an IOError, as there are just two tabs there.

**Comment by st-pasha** [comment]
Thanks Darel, I was able to reproduce the error using the data file you provided.

cc @pradkrish 
The problem here is that at the parse settings detection stage quoting rule 0 is detected, but later on there is a line
```
51372\t"Great Performances" Cats (1998)\tMusical
``` 
This can only be parsed with QR=3. However, it tries QR=2 first, and under that rule there are 2 fields only.

**Comment by pradkrish** [comment]
@st-pasha so given the separator, `\t` in this case, if a lower order QR (2 in this case) can parse a row that a higher order QR (3 in this case) can also parse, we end up prioritising the parsed value of  the lower order QR, is it?
