### ISSUE TITLE
Datatable installation causes conda list to break down

### ISSUE THREAD

**Issue by lucasjamar** [h2oai/datatable#2746]
- Did you find a bug in datatable, or maybe the bug found you?
Installing datatable through pip breaks "conda list" command. Uninstalling datatable makes "conda list" work fine again. The error message is attached.

- How to reproduce the bug?
1. Created new virtual environement in anaconda3
2. Installed datatable through pip
3. Run "conda list"
4. Get error message

- What was the expected behavior?
List of conda and pip packages

- Your environment?
datatable 0.11.0
Python 3.8.5
conda 4.9.1
Windows 10 Enterprise

![image](https://user-images.githubusercontent.com/39372418/99079743-a52bed00-25c0-11eb-8f55-d8daedc79725.png)

**Comment by st-pasha** [comment]
I believe this is the same error as reported at https://github.com/conda/conda/issues/10006.

**Comment by lucasjamar** [comment]
ok. A conda issue then. Thx :)

**Comment by mlisovyi** [comment]
Hmm.

- The issue on conda is there since June and there has been no reaction.
- Plus one installs it via pip instead of conda.
- Plus it is likely a problem with the pip package itself which maybe does not conform with the conda expectations.

So i'm not sure the issue on conda has a chance for success :(

But this issue with v 0.11.0 is a real bummer and prevents me as user to use this version :(

**Comment by mlisovyi** [comment]
Thanks @st-pasha for the fast implementation of a fix!

**Comment by st-pasha** [comment]
we'll still need to make a new release  0.11.1 so that the fix is available to the public
