### ISSUE TITLE
Should NA equals NA in comparison?

### ISSUE THREAD

**Issue by zhangyingmath** [h2oai/datatable#2787]
Here is what I see: 
```
DT = dt.Frame({'f': [1,2,3, np.nan]})
df = pd.DataFrame({'f': [1,2,3, np.nan]})

df.loc[df.f == df.f].shape
(3, 1)

DT[dt.f.f == dt.f.f, :].shape
(4, 1)
```

I believe the issue is rooted in the python behavior that 
```
None == None
True

np.nan == np.nan
False
```

I am curious if the datatable behavior above is a conscious choice, or not. Being a long-time pandas user, I personally think the pandas/numpy behavior (NA does not equal NA) acceptable. I am curious what the datatable team thinks of this.

**Comment by samukweku** [comment]
@zhangyingmath , this is just a guess, but I believe `np.nan` is turned to None (`NA`) within datatable. As such, `None==None` returns `True`.

**Comment by st-pasha** [comment]
Well, this is a rather philosophical question.

On one hand, the axiom of reflexivity postulates that every value is equal to itself. This implies that `NA==NA` is True. It is possible to reject this axiom and postulate that *some* values (such as NA) are not equal to themselves. However, if we do accept the axiom, it becomes easy to reason about the properties of the `==` relation. In particular, every column in a frame is equal to itself, and every frame is equal to itself too.

Now, as you correctly pointed out, some people reject full reflexivity and postulate that `NA==NA` is False. Why would that be a case? We'd have to look at what "NA" actually mean. It turns out there could be multiple different kinds of NAs:

- An NA could mean "not a number", i.e. a special value that signals an error in a calculation. For example, `ln(-1)` or `arcsin(10)` both produce NAs (alternatively, they could have thrown an exception instead). In this case "NA" is just an error object, and there is little reason to say that one error should be different from another.

- An NA could also mean "not applicable". For example, if you have a dataset with data on how many children there are in a  family, and what is the ages of youngest and oldest of the children, then for a family with 0 children the last two fields will be NAs. In this case, again, the records of two families both having 0 children should compare equal. Thus, in this case `NA==NA` is again True.

- An NA could also mean "not available" (aka "missing"). Unlike the previous case, the data does *exist* somewhere, it's merely not known in the dataset. In this case NA value is akin to a black box, and it therefore can be argued that two NA values are not equal to each other: their underlying hidden values could be different. But they could also be the same, we just don't know. Thus, in this case the result of comparison `NA==NA` is itself NA, i.e. not known.

We may also mention another special number here: infinity. Well, technically it's not a number, it's a symbol. But in numpy it can indicate either the value that is truly infinite, or merely large enough to not fit into float64. Even though they are not numbers, they compare as equal:
```
>>> np.inf == np.inf
True
```
This is despite the fact that those infinities can represent demonstrably unequal quantities:
```
>>> (np.float64(10) ** np.float64(1000)) == (np.float64(10) ** np.float64(1000000))
True
```

We use the same approach with NAs as with infinities: each value is equal to itself. This just seems more consistent and easier to reason about.
