### ISSUE TITLE
rbind on columns with different types

### ISSUE THREAD

**Issue by zhangyingmath** [h2oai/datatable#2790]
I really like the fact that when I try to set a float value to part of an integer column, like `DT = dt.Frame{'f':[1,2,3,4]}, DT[0, 'f'] = 1.1`, I got an error. This is great, since the error is explicit and the user can readily take action. (But assigning int value to float columns is fine, which is what I expect). Given this relative "strict" requirement on types in datatable (compared with pandas), I am a bit surprised to see that a similar "type check" is not enforced at rbind. 

```
DT1 = dt.Frame{'f': [1,2,3,4]}
DT2 = dt.Frame{'f': [1.1,2.2,3.3,4.4]}
DT3 = dt.Frame({'f': list('abcd')})
```
 
Then, `dt.rbind([DT1, DT2])` gives a real column, which is perfectly fine. But `dt.rbind([DT1, DT3])` and `dt.rbind([DT2, DT3])` both give str columns as a result, which in my personal opinion is a bit too lenient. (Btw, this behavior similar to `np.concat`.)

I am curious what you think about the following: 

1. Change the default behavior to raise an error when a numeric column and a str column were to be concat.
2. Adding a keyword argument to rbind and let the user decide whether they want to raise an error in this case, or turn everything into a str.

**Comment by samukweku** [comment]
Hi @zhangyingmath ,

[rbind()](https://datatable.readthedocs.io/en/latest/api/frame/rbind.html) has a rule in terms of its promotion:
> If frame(s) being appended have columns of types different from the current frame, then these columns will be promoted to the largest of their types: bool -> int -> float -> string.

As such, ``dt.rbind(DT1, DT2)`` and ``dt.rbind(DT1, DT3)`` are promoted to strings, based on the promotion rule. I personally think it's fine, the library authors however may have a different opinion.

@st-pasha @oleksiyskononenko

**Comment by st-pasha** [comment]
I agree with @zhangyingmath here: too much of automatic type promotion causes problems.

In general, we'd like to have a consistent set of rules that governs type promotion across all functions in datatable. For example, if we were to apply rbind's rules to binary functions, then we'll get things like `"1" + 2 = "12"` or `"3" == 3`. This is the kind of things Javascript does, and it's generally considered not a good design (they even had to invent the `===` operator in order to avoid the problems caused by this kind of automatic type promotion).

So, going into the future I'd like to keep automatic type promotion `bool -> int -> float`, but disable the promotion into `string` or `date`.
