### ISSUE TITLE
[BUG] as_type conversion from float to int

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#2905]
- Did you find a bug in datatable, or maybe the bug found you?
  `as_type` returns a value different from what is expected, especially when converting from float to int.

- How to reproduce the bug?
```python

df = {'V1': [1.0, 4.0, 1.0, 4.0, 1.0, 4.0, 1.0, 4.0, 1.0],
 'V2': [0.0,
  0.0,
  0.0,
  4.0,
  5.000000000000001,
  5.999999999999999,
  7.000000000000001,
  8.000000000000002,
  9.0],
 'V4': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C']}

df = dt.Frame(df)

df

   |      V1       V2  V4   
   | float64  float64  str32
-- + -------  -------  -----
 0 |       1        0  A    
 1 |       4        0  B    
 2 |       1        0  C    
 3 |       4        4  A    
 4 |       1        5  B    
 5 |       4        6  C      # this is where the change occurs when applying as_type
 6 |       1        7  A    
 7 |       4        8  B    
 8 |       1        9  C    
[9 rows x 3 columns]


df[:, dt.as_type(f.V2, int)]

   |    V2
   | int64
-- + -----
 0 |     0
 1 |     0
 2 |     0
 3 |     4
 4 |     5
 5 |     5       # value changes to 5, instead of 6
 6 |     7
 7 |     8
 8 |     9
[9 rows x 1 column]

 ```

Earlier when I ran this `dt.int32` returned 6, as expected; now it is consistent with `as_type`. Any particular reason for this approach? 

- What was the expected behavior?
  I would expect the value to be 6, not 5.

- Your environment?
   ```
       datatable version : '1.0.0a0+build.1615412817.sam'
       python version: '3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) \n[GCC 9.3.0]'
       operating system: Linux (Ubuntu)
   ```

**Comment by st-pasha** [comment]
There is no bug here: floats are converted to integers by truncating their fractional parts. Same happens in pure python too (and in all other languages that I am aware of):
```
>>> int(5.999999999999999)
5
```

At the same time, when float values are displayed in a terminal, we use C++'s `operator<<(double)` to print the value. By default, this method rounds the double value to 6 decimal places (see [this SO question](https://stackoverflow.com/questions/33854825)), which is why the value appears as `"6"`.

There are ways to improve the current behavior, for example create an option for the number of significant digits displayed.

**Comment by samukweku** [comment]
Thanks for the clarification @st-pasha . Closing this.
