### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#2965]
- Did you find a bug in datatable, or maybe the bug found you?
I upgraded my dev version to the most recent, and got an Import Error.

- How to reproduce the bug?
```python
pip install git+https://github.com/h2oai/datatable

ImportError: /home/sam/miniforge3/envs/rubbish/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/sam/miniforge3/envs/rubbish/lib/python3.8/site-packages/datatable/lib/_datatable.cpython-38-x86_64-linux-gnu.so)

```

- What was the expected behavior?
Any suggestions on how to resolve this. I have updated to the latest gcc -`gcc11.0.1`

- Your environment?
- datatable version 1.0
- python version 3.9
- Linux

**Comment by samukweku** [comment]
@st-pasha @oleksiyskononenko if there is a docker option, I'll appreciate that as well

**Comment by econwang** [comment]
it seems that you use different version of libstdc++ when compile and call the datatable library. Several distributions like anaconda use their own packaged libstdc++, this can be different from the system version, which is the one you compile the library. A simple fix is that replace the libstdc++ in python env with the system one, that is (the path maybe different in your env)

```
sudo ln -s /usr/lib64/libstdc++.so.6 /path2python/lib/libstdc++.so.6
```

since libstdc++ is backward compatible, this operation should not cause compatibility issue for other python libs that depend on it.

**Comment by samukweku** [comment]
@econwang thanks ... I actually tried that ... No luck. Any other ideas are welcome. Thanks

**Comment by st-pasha** [comment]
It appears that pip was able to successfully install datatable (at least `_datatable.CPython-38-x86_64-linux-gnu.so` was created), but it can't be imported because of a GLIBC version mismatch. The only way I think this could happen is if your `pip` runs in a different environment than your python. Somehow. I guess more information can be gleaned if you run pip in verbose mode (`-vvv`).

As for "docker version", this is actually quite simple. You can see in `ci/Jenkinsfile.groovy` how we build datatable: pull docker image `quay.io/pypa/manylinux2010_x86_64`, then within that image git-clone the datatable directory and in that directory run a single command `/opt/python/cp38-cp38/bin/python3.8 ci/ext.py wheel --audit`. This will produce a wheel file directly installable on most linux systems. 

You can also check out https://h2o-release.s3.amazonaws.com/datatable/index.html where we put all wheels from our CI system -- just scroll to the bottom of the page and grab a link that corresponds to your system.

**Comment by samukweku** [comment]
thanks @st-pasha @econwang  - created a new environment, and installed gcc/g++ before installing datatable ... I still cant figure out why it stopped working ... it works now so I'll move on. Followed the guide on this [page](https://seanlaw.github.io/2019/01/17/pip-installing-wheels-with-conda-gcc/) for the installation and the symbolic link
