### ISSUE TITLE
[bug] Applying the pow function change the column name

### ISSUE THREAD

**Issue by argenisleon** [h2oai/datatable#3209]
- Did you find a bug in datatable, or maybe the bug found you?
  When applying the pow function over a column it changes the name to C0

- How to reproduce the bug?

```
pdf = pd.DataFrame({'A': ["True", "30345", "2", None, "1", "2"],
               'B': [None, 2, 3, 4, None, 5],
               'C': [1, 2, 1, 1, 2, 4]})
df = dt.Frame(pdf)
df[:,dt.math.pow(f.B,2)]

   |      C0
   | float64
-- + -------
 0 |      NA
 1 |       4
 2 |       9
 3 |      16
 4 |      NA
 5 |      25
[6 rows x 1 column]

```

- What was the expected behavior?
Preserve the name of the column. In this case `B`

- Your environment?
  What is your datatable version, python version, and operating system?
datatable 1.1.0a2099
python 3.8.8
windows 11

**Comment by oleksiyskononenko** [comment]
Well, I don't think we have ever documented `pow()` to preserve column names. That's because binary functions take two arguments, so we don't know which column name to preserve. For instance, the call could be anything of the following
- `pow(f.B, 2)`
- `pow(2, f.B)`
- `pow(2, 2)`
- `pow(f.A, f.B)`
and right now all of these calls will result in the column `C0` to be created. Yes, we can assign column names based on some logic, but I'm not sure this logic will be intuitive to everyone.

**Comment by oleksiyskononenko** [comment]
Closing. Feel free to reopen if you have some thoughts on how the column name should be generated to binary functions.
